# Generated by Django 5.2.17 on 2026-09-20 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="access",
            options={
                "verbose_name": "guardian access",
                "verbose_name_plural": "guardian access grants",
            },
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "verbose_name": "notification delivery",
                "verbose_name_plural": "notification deliveries",
            },
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("controller", True)),
                fields=("profile",),
                name="one_active_controller",
            ),
        ),
    ]
