# Generated by Django 5.2.17 on 2026-09-20 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0003_object_first"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        limit_choices_to={"kind": "family"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to="labels.profile",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        limit_choices_to={"kind__in": ["child", "adult"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_links",
                        to="labels.profile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "member"), name="one_family_membership"
                    )
                ],
            },
        ),
    ]
