import { useState, type FormEvent } from "react";
import { api } from "../api";
import { GuardianAccess } from "../components/GuardianAccess";
import type { Belonging, Profile, RunAction, User } from "../types";
const kinds = {family:'Family',child:'Child',adult:'Adult'};
export function ManageFamily({profiles, objects, user, run, busy, viewObjects}: {profiles:Profile[]; objects:Belonging[]; user:User; run:RunAction; busy:boolean; viewObjects:(id:string)=>void}) {
  const [family, setFamily] = useState('all'); const [kind, setKind] = useState('all');
  const [showArchived, setShowArchived] = useState(false); const [editing, setEditing] = useState<string|null>(null);
  const [creating, setCreating] = useState<Profile['kind']|null>(null); const [confirmArchive,setConfirmArchive]=useState(false);
  const families=profiles.filter(p=>p.kind==='family'&&!p.archived);
  const managedFamilies=families.filter(p=>p.controller);
  const selected=profiles.find(p=>p.id===editing);
  const visible=profiles.filter(p=>(showArchived||!p.archived)&&(kind==='all'||p.kind===kind)&&(family==='all'||p.id===family||p.families.includes(family)));
  async function create(e:FormEvent<HTMLFormElement>) {e.preventDefault();const form=e.currentTarget;const data=new FormData(form);await run(async()=>{const profile=await api<{id:string}>('profiles/','POST',{name:data.get('name'),kind:creating,...(data.get('family')?{family:data.get('family')}: {})});setEditing(profile.id);setCreating(null);setKind('all');},'Profile created. Its name stays private.');}
  return <>
    <div className="page-heading"><div><p className="eyebrow">Room for every kind of family</p><h1>Manage family</h1><p>Keep children, adults and family groups organized. Choose guardian access separately for each profile.</p></div></div>
    <div className="button-row family-actions"><button disabled={busy} onClick={()=>setCreating('child')}>Add child</button><button className="secondary" disabled={busy} onClick={()=>setCreating('adult')}>Add adult</button><button className="secondary" disabled={busy} onClick={()=>setCreating('family')}>Create family group</button></div>
    {creating&&<section className="panel creation-panel" key={creating}><div className="button-row"><h2>{creating==='family'?'Create a family group':`Add ${creating==='adult'?'an adult':'a child'}`}</h2><button className="text-button" onClick={()=>setCreating(null)}>Cancel</button></div><form onSubmit={create}>
      <label>{creating==='family'?'Family name':creating==='child'?'Child’s name or nickname':'Adult’s name'}<input autoFocus name="name" required maxLength={80} autoComplete="off"/></label>
      <p className="hint">Used in your private dashboard. It will not appear on labels or scan pages automatically. No birth date, school or address is needed.</p>
      {creating!=='family'&&<label>Family group (optional)<select name="family" defaultValue={managedFamilies.some(f=>f.id===family)?family:''}><option value="">Keep independent for now</option>{managedFamilies.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}
      {creating==='adult'&&<p className="hint">This is a profile for an adult’s belongings. To give someone their own account access, invite them as a guardian instead.</p>}
      <button disabled={busy}>Save {creating==='family'?'family group':creating}</button></form></section>}
    <div className="panel filter-bar"><label>Family group<select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All profiles I can access</option>{families.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Profile type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Children, adults & families</option><option value="child">Children</option><option value="adult">Adults</option><option value="family">Family groups</option></select></label><label className="check"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Show archived profiles</label></div>
    {!visible.length&&<div className="panel empty-state"><h2>{profiles.length?'No profiles match this view':'Start with your family'}</h2><p>Add a child, adult or family group. You can link shared children to more than one family group.</p></div>}
    <div className="profile-grid">{visible.map(p=><article className={`panel profile-card ${editing===p.id?'selected-card':''}`} key={p.id}><div className={`profile-avatar ${p.kind}`} aria-hidden="true">{p.name.slice(0,1).toUpperCase()}</div><span className="tag">{kinds[p.kind]}{p.archived?' · Archived':''}</span><h2>{p.name}</h2><p className="hint">{p.controller?'You manage this profile':'Shared with you'}{!p.archived&&` · ${objects.filter(o=>o.profile===p.id).length} objects`}</p>
      {p.kind!=='family'&&<p className="hint">{p.families.length?p.families.map(id=>profiles.find(f=>f.id===id)?.name).filter(Boolean).join(' · '):'Independent profile'}</p>}
      <div className="button-row"><button className="secondary" onClick={()=>{setEditing(p.id);setConfirmArchive(false);}}>Manage {p.name}</button>{!p.archived&&<button className="text-button" onClick={()=>viewObjects(p.id)}>View objects for {p.name}</button>}</div></article>)}</div>
    {selected&&<section className="panel profile-detail" key={selected.id}><div className="button-row"><h2>Manage {selected.name}</h2><button className="text-button" onClick={()=>setEditing(null)}>Close details</button></div>
      {selected.controller?<form className="management-section" onSubmit={e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name');run(()=>api(`profiles/${selected.id}/`,'PATCH',{name}),'Private profile name updated. Printed and online text are unchanged.');}}><label>Private profile name<input name="name" required maxLength={80} defaultValue={selected.name}/></label><button disabled={busy}>Save name</button></form>:<p className="hint">Only the profile manager can rename, archive or manage invitations. You can manage its objects and your own alerts.</p>}
      {!selected.archived&&<section className="management-section"><h3>Your notifications</h3><label className="check"><input type="checkbox" disabled={busy||!user.email_verified} checked={selected.email_alerts} onChange={e=>run(()=>api(`profiles/${selected.id}/preferences/`,'PATCH',{email_alerts:e.target.checked}),'Your notification preference was saved.')}/>Email me when an object belonging to {selected.name} is found</label>{!user.email_verified&&<p className="hint">Verify your email on the Account page to enable alerts.</p>}</section>}
      {selected.kind==='family'&&!selected.archived&&<section className="management-section"><h3>Children & adults in this group</h3><p className="hint">Only profiles you can access are shown. Linking a profile does not share it with other guardians. A child can belong to more than one group.</p>
        <ul className="people-list">{selected.members.map(id=>profiles.find(p=>p.id===id)).filter((p):p is Profile=>!!p).map(p=><li key={p.id}><span>{p.name}<small>{kinds[p.kind]}{p.archived?' · Archived':''}</small></span>{selected.controller&&<button className="text-button" disabled={busy} onClick={()=>run(()=>api(`families/${selected.id}/members/${p.id}/`,'DELETE'),'Profile unlinked. Guardian permissions and objects are unchanged.')}>Unlink {p.name}</button>}</li>)}</ul>
        {selected.controller&&<form onSubmit={e=>{e.preventDefault();const profile=new FormData(e.currentTarget).get('profile');run(()=>api(`families/${selected.id}/members/`,'POST',{profile}),'Profile linked. Guardian access is unchanged.');}}><label>Link an existing child or adult<select name="profile" required defaultValue=""><option value="" disabled>Choose a profile</option>{profiles.filter(p=>p.kind!=='family'&&!p.archived&&!selected.members.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name} · {kinds[p.kind]}</option>)}</select></label><button disabled={busy||!profiles.some(p=>p.kind!=='family'&&!p.archived&&!selected.members.includes(p.id))}>Link to family</button></form>}
      </section>}
      {selected.controller&&!selected.archived&&<GuardianAccess profile={selected} user={user} run={run} busy={busy}/>}
      {selected.controller&&<section className="management-section archive-section"><h3>{selected.archived?'Restore profile':'Archive profile'}</h3><p className="hint">{selected.archived?'Restoring keeps existing records. QR codes and email alerts stay off until enabled again.':'Archiving keeps records but disables this profile’s QR codes and alerts, and cancels pending invitations. Linked children or other family profiles are unaffected.'}</p>
        {selected.archived?<button className="secondary" disabled={busy} onClick={()=>run(()=>api(`profiles/${selected.id}/`,'PATCH',{archived:false}),'Profile restored. Re-enable QR codes and alerts when ready.')}>Restore {selected.name}</button>:confirmArchive?<div className="inline-confirm"><p>Archive {selected.name} and disable its labels?</p><button disabled={busy} onClick={async()=>{if(await run(()=>api(`profiles/${selected.id}/`,'PATCH',{archived:true}),'Profile archived. Use “Show archived profiles” to restore it.')){setEditing(null);setConfirmArchive(false);if(family===selected.id)setFamily('all');}}}>Confirm archive</button><button className="text-button" onClick={()=>setConfirmArchive(false)}>Cancel</button></div>:<button className="secondary" onClick={()=>setConfirmArchive(true)}>Archive {selected.name}</button>}
      </section>}
    </section>}
  </>;
}
