import { useState } from "react";
import { api } from "../api";
import { LabelEditor } from "../components/LabelEditor";
import type { Belonging, Profile, RunAction } from "../types";
export function Objects({objects,profiles,selected,setSelected,run,busy,addToSheet,manageFamily}: {objects:Belonging[];profiles:Profile[];selected:string;setSelected:(id:string)=>void;run:RunAction;busy:boolean;addToSheet:(id:string)=>void;manageFamily:()=>void}) {
  const [creating,setCreating]=useState(false);const [search,setSearch]=useState('');const [showDisabled,setShowDisabled]=useState(false);
  const [share,setShare]=useState(false); const [publicText,setPublicText]=useState('');
  const active=profiles.filter(p=>!p.archived);const target=active.find(p=>p.id===selected);
  const visible=objects.filter(o=>(selected==='all'||o.profile===selected)&&(showDisabled||o.label.active)&&`${o.name} ${o.profile_name}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="page-heading"><div><p className="eyebrow">A place for every belonging</p><h1>Objects</h1><p>Create a specific item or a reusable group, then print as many labels as you need.</p></div><button disabled={!active.length} onClick={()=>setCreating(!creating)}>{creating?'Close new object':'Add object'}</button></div>
    {!active.length&&<div className="panel empty-state"><h2>Add someone to your family first</h2><p>Objects belong to a child, adult or family profile.</p><button onClick={manageFamily}>Manage family</button></div>}
    {creating&&<section className="panel creation-panel"><h2>Add an object</h2><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);if(await run(()=>api('objects/','POST',{profile:data.get('profile'),name:data.get('name'),kind:data.get('kind'),print_text:data.get('print_text'),public_text:publicText,share_text:share}),'Object created. Add copies on the Print labels page.')){form.reset();setShare(false);setPublicText('');setCreating(false);}}}>
      <label>Belongs to<select name="profile" required value={target?.id||''} onChange={e=>{setSelected(e.target.value);setShare(false);}}><option value="" disabled>Choose a profile</option>{active.map(p=><option key={p.id} value={p.id}>{p.name} · {p.kind}</option>)}</select></label>
      <label>Object name<input name="name" maxLength={100} required placeholder="Laptop, calculator, clothing…"/></label><label>Object type<select name="kind"><option value="item">Specific item</option><option value="group">Reusable group of belongings</option></select></label>
      <label>Text printed under the QR (optional)<input name="print_text" maxLength={80} placeholder="A name or short message"/></label><p className="hint">Printed text is visible on the sticker. Object names are private and are not printed automatically.</p>
      <label>Scan-page text (optional)<textarea maxLength={200} value={publicText} onChange={e=>setPublicText(e.target.value)}/></label><label className="check"><input type="checkbox" checked={share} disabled={!target?.controller} onChange={e=>setShare(e.target.checked)}/>Show this text to anyone scanning the QR</label>
      <div className="privacy-preview"><strong>Scanner will see</strong><p>{share&&publicText?publicText:'Generic return guidance. No personal information.'}</p><small>Plus a private message form.</small></div><button disabled={busy||!target}>Create object</button>
    </form></section>}
    <div className="panel filter-bar"><label>Belongs to<select value={selected} onChange={e=>{setSelected(e.target.value);setShare(false);}}><option value="all">All profiles</option>{active.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Search objects<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or person"/></label><label className="check"><input type="checkbox" checked={showDisabled} onChange={e=>setShowDisabled(e.target.checked)}/>Show disabled codes</label></div>
    {!visible.length&&active.length>0&&<div className="panel empty-state"><h2>No objects match this view</h2><p>Add an object or adjust your filters.</p></div>}
    <div className="label-grid">{visible.map(o=>{const l=o.label;const controller=!!profiles.find(p=>p.id===o.profile)?.controller;return <article key={o.id} className="panel label-card"><span className="tag">{o.kind==='group'?'Reusable group':'Specific item'}{!l.active?' · Disabled':''}</span><h2>{o.name}</h2><p className="hint">Belongs to {o.profile_name}</p><p>{l.print_text||'No printed text'}</p><p className="hint">Online text: {l.share_text?l.public_text||'(empty)':'hidden'}</p><div className="button-row"><button disabled={!l.active} onClick={()=>addToSheet(o.id)}>Add to print sheet</button><a className="button secondary" href={l.scan_url} target="_blank" rel="noreferrer">Preview scan</a></div>
      <details><summary>Rename object</summary><form onSubmit={e=>{e.preventDefault();run(()=>api(`objects/${o.id}/`,'PATCH',{name:new FormData(e.currentTarget).get('name')}),'Object renamed. Its QR code is unchanged.');}}><label>Private object name<input name="name" required maxLength={100} defaultValue={o.name}/></label><button disabled={busy}>Save object name</button></form></details>
      <LabelEditor label={l} controller={controller} busy={busy} save={changes=>run(()=>api(`labels/${l.id}/`,'PATCH',changes),'Label text saved.')}/>
      <button className="text-button" disabled={busy||(!l.active&&!controller)} onClick={()=>run(()=>api(`labels/${l.id}/`,'PATCH',{active:!l.active}),l.active?'QR disabled.':'QR enabled.')}>{l.active?'Disable QR':'Enable QR'}</button>
      {l.share_text&&<button className="text-button" disabled={busy} onClick={()=>run(()=>api(`labels/${l.id}/`,'PATCH',{share_text:false}),'Public text hidden.')}>Hide online text</button>}
    </article>;})}</div>
  </>;
}
